runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  CLOUD_SQL_USERNAME: mastershoe
  CLOUD_SQL_PASSWORD: shoe
  CLOUD_SQL_DATABASE_NAME: shoe_store
  CLOUD_SQL_CONNECTION_NAME: css475aw23shoestore:us-west1:cloud-shoe-store-sql 
# [END gae_python37_cloudsql_config]
